name: softball-stat-tracker
component: website               # (required) name of the component. In that case, it's website.
stage: dev                       # (optional) serverless dashboard stage. default is dev.

inputs:
  region: us-east-2              # (optional) aws region to deploy to. default is us-east-1.\
  domain: softballstattracker.com
  src:
    src: ./src          # the input source folder
    hook: npm run build # the hook you want to run
    dist: ./dist        # the output dist folder